[config]

# btop
[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook =   'pkill -USR2 btop || true'

# gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

# gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

# steam
[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'flatpak run io.github.Foldex.AdwSteamGtk -i'

# swaync 
[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'

# wezterm
[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm.toml'
output_path = '~/.config/wezterm/colors/matugen-theme.toml'
post_hook = 'touch ~/.config/wezterm/wezterm.lua'

# wofi
[templates.wofi]
input_path = '~/.config/matugen/templates/wofi.css'
output_path = '~/.config/wofi/themes/matugen.css'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

